### ISSUE TITLE
Back to top should be visible if there is an enough vertical space

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#130]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
Back to top button is shown if the viewport height is 150px.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check the home page in a phone landscape mode.

<img width="654" alt="screen shot 2017-03-19 at 8 43 37 pm" src="https://cloud.githubusercontent.com/assets/8038659/24083675/4afbd60e-0ce4-11e7-8419-0b323afa8b48.png">

**- What is the expected behavior?**
Back to top button should be visible only when there is an enough vertical space. For example

```css
.back-to-top {
   display: none;
}

@media (min-height: 800px) {
  .back-to-top {
     display: block;
  }
}
```

I think it will be better that way, since there is no benefit for making it visible when as a user, I'm already at the top of the page.
