### ISSUE TITLE
Related jobs avatars are broken

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#152]
**- Do you want to request a *feature* or report a *bug*?**
Bug.

**- What is the current behavior?**
Avatars are distorted in a weird way.

<img width="311" alt="screen shot 2017-03-21 at 6 32 04 am" src="https://cloud.githubusercontent.com/assets/8038659/24132751/75411844-0e00-11e7-9d49-4280b5777c0c.png">

**- If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://next.smashingmagazine.com/jobs/2017-1-31-reactengineer-russiaandukraine-foxcommerce-remote-russiaukrainepoland-fulltime/ and check the related jobs module.

**- What is the expected behavior?**
<img width="187" alt="screen shot 2017-03-21 at 6 39 30 am" src="https://cloud.githubusercontent.com/assets/8038659/24132754/7ac876d6-0e00-11e7-8f6a-9027b53a4df1.png">

Also, kindly note that all of the below commented CSS is not needed since we have `position: absolute`.

```css
.job-details__related-jobs .author {
    /* display: inline-block; */
    /* float: none; */
    /* vertical-align: middle; */
    /* position: relative; */
    top: -.2em;
    /* margin-right: .5em; */
    position: absolute;
    left: 0;
}
```

**- Please mention your operating system version and the version of your browser**
Latest Chrome on OSX.
