### ISSUE TITLE
Conferences menu icon alignment in Edge

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#159]
**- Do you want to request a *feature* or report a *bug*?**
An enhancement.

**- What is the current behavior?**
The icon is not aligned well.

![virtualbox_ms edge_21_03_2017_10_18_46](https://cloud.githubusercontent.com/assets/8038659/24138339/877fb93c-0e20-11e7-9537-bdae720f1ab8.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Check the conference list menu for https://next.smashingmagazine.com/events/san-francisco-2017/

**- What is the expected behavior?**

<img width="444" alt="screen shot 2017-03-21 at 10 20 51 am" src="https://cloud.githubusercontent.com/assets/8038659/24138058/5de64966-0e1f-11e7-83a1-d80f826995e6.png">

Removing the commented CSS:

```css
.form__field--checkbox .form__field__label>span {
    display: block; /* no need for this because we have float: right */
    /* margin-top: .4em; */
}

.conf-locations-toggle-label .more {
    float: right;
    position: relative;
    /* top: -.4em; */
    font-size: 1.5em;
    transition: all .2s ease-in-out;
}
```

Since the icon is text, it's possible to control the spacing by adding `line-height`:

```css
.conf-locations-toggle-label .more {
   line-height: 30px;
}
```
With that solution, we don't need `top` and `margin-top` properties. Tested that in Chrome, Firefox and Edge.

**- Please mention your operating system version and the version of your browser**
Edge 38.14393
