### ISSUE TITLE
An area of the ticket select menu is not clickable

### ISSUE THREAD

**Issue by shadeed** [smashingmagazine/redesign#50]
I clicked on the select menu to see the options. I noticed that an area is not clickable, due to the label "Workshop"
![screen shot 2017-03-17 at 10 28 08 am](https://cloud.githubusercontent.com/assets/8038659/24035183/35867bdc-0afd-11e7-9798-7e67ee3ed377.jpg)

In that case it's a small area, but if the label longer? A bigger area will prevent activating the options.

![screen shot 2017-03-17 at 10 34 47 am](https://cloud.githubusercontent.com/assets/8038659/24035239/60a20a02-0afd-11e7-84d5-a32089222c82.jpg)

Adding `pointer-events: none` to the label would prevent that issue. 

```css
.enhanced .form__row--workshop-selection .form__field__label {
    color: #F6F3F2;
    z-index: 2;
   /* Addition */
   pointer-events: none;
}
```
