### ISSUE TITLE
figure caption icon bigger than the image to which the caption pertain on MS Edge

### ISSUE THREAD

**Issue by avvertix** [smashingmagazine/redesign#76]
**- Do you want to request a *feature* or report a *bug*?**

*bug*

**- What is the current behavior?**

The icon in the figure caption *before* is very big

![image](https://cloud.githubusercontent.com/assets/5672748/24042862/29e381f0-0b14-11e7-8e9a-0956ed9d0c2c.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

- Go to https://next.smashingmagazine.com/2017/03/a-little-surprise-is-waiting-for-you-here--meet-the-next-smashing-magazine/ with Edge on Windows 10
- scroll until the first figure
- you will see the photocamera icon in the figure caption very big

**- What is the expected behavior?**

- The icon should be the same height of the font size

**- Please mention your operating system version and the version of your browser**

- Windows 10 (1607 build 14393.953)
- Microsoft Edge 38.14393.0.0 (EdgeHTML 14.14393)

**Comment by dstorey** [comment]
Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11316778/

Relates to SVG images not resizing in display table.

**Comment by vitalyfriedman** [comment]
Ouch — any way to resolve the Edge bug issue @dstorey?

**Comment by avvertix** [comment]
@vitalyfriedman @pukhalski @dstorey I tried a little bit with live editing the CSS, indeed Edge seems to suffer of bugs in the latest release, but I think I've been able to obtain a decent result by adding `line-height:1.2` to the `figcaption` style and force `display: inline-block` on the `::before` pseudo-element

```css
.article__content figure figcaption,.article__image figcaption {
    color: #666;
    font-size: calc(.8em + .2vw);
    font-style: italic;
    padding: .75em 0;
    display: table;
    line-height: 1.2;
}
.article__content figure figcaption::before,.article__image figcaption::before {
    content: url(data:image/svg+xml;...);
    width: 1.5em;
    padding-right: .6em;
    display: inline-block;
    vertical-align: baseline;
    position: relative;
    top: .05em;
}
```

The image below shows (1) the original page and (2) the version with the above mentioned hack

![image](https://cloud.githubusercontent.com/assets/5672748/24079251/99518af8-0c83-11e7-9ad8-af5db3d37aa0.png)

Hope it helps
